name: video-encoder-ci
on:
  pull_request:
    branches:
      - main
jobs:
  check-app-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - run: go test -v ./...
      - run: go run .

      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Docker Build and Push
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          push: false
          tags: xstrato/video-encoder-golang:latest
