name: video-encoder-ci
on:
  pull_request:
    branches:
      - main
jobs:
  check-app-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - run: go test
